### ISSUE TITLE
ERROR: dependency 'digest' is not available for package 'dwtools'

### ISSUE THREAD

**Issue by Breal76** [jangorecki/dwtools#5]
Tried to install dwtools in RStudio 1.1447 with R version 3.5.

The downloaded binary packages are in
	C:\Users\XX\AppData\Local\Temp\Rtmpwjx7st\downloaded_packages
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/XX/AppData/Local/Temp/Rtmpwjx7st/devtools68082ebf231c/jangorecki-dwtools-2a0ee31"  \
  --library="C:/Users/XX/Documents/R/win-library/3.5" --install-tests 

ERROR: dependency 'digest' is not available for package 'dwtools'
* removing 'C:/Users/XX/Documents/R/win-library/3.5/dwtools'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by jangorecki** [comment]
do you have `digest` package installed?

**Comment by Breal76** [comment]
Aha! Boom, fixed. Gracias!
